version: "3.8"
services: 
  # database container config
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpressgedanggoreng
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    networks:
      - wpsite
  # wordpress container config
  wordpress:
    depends_on: 
      - db
    image: wordpress:latest
    ports: 
      - '8080:80'
    restart: always
    volumes: ['./wordpress:/var/www/html']
    environment: 
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpressgedanggoreng
    networks: 
      - wpsite
networks: 
  wpsite:
volumes: 
  db_data: